# Generated by Django 3.0.7 on 2020-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dnb_service_duns_number',
            field=models.IntegerField(),
        ),
    ]
