version: '3'
services:

  node_modules:
    image: node:12-slim
    working_dir: /app
    volumes:
      - ./backoffice:/app
    command: npm i

  backoffice_db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    env_file: backoffice/.env
    volumes:
      - backoffice_db_data:/var/lib/postgresql/data/

  backoffice:
    build:
      context: ./backoffice
      dockerfile: Dockerfile
    env_file: backoffice/.env
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backoffice:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - node_modules
      - backoffice_db

volumes:
  backoffice_db_data:
