# Generated by Django 3.0.7 on 2020-08-05 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='application_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
