# Generated by Django 3.1.1 on 2020-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0003_remove_grantapplication_has_previously_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='is_intending_on_other_financial_support',
        ),
    ]
