# Generated by Django 3.0.7 on 2020-08-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('grant_applications', '0004_auto_20200811_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='duns_number',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.Company'),
        ),
    ]
