# Generated by Django 3.1.1 on 2020-10-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0004_remove_grantapplication_is_intending_on_other_financial_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='is_based_in_uk',
        ),
    ]
