# Generated by Django 3.1.1 on 2020-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0005_remove_grantapplication_is_based_in_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='applicant_position_within_business',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='job_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
