# Generated by Django 3.1.1 on 2020-10-28 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0006_auto_20201028_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplication',
            old_name='turnover',
            new_name='previous_years_export_turnover_1',
        ),
        migrations.RenameField(
            model_name='grantapplication',
            old_name='goods_and_services_description',
            new_name='products_and_services_description',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_years_export_turnover_2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_years_export_turnover_3',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_years_turnover_1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_years_turnover_2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_years_turnover_3',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='products_and_services_competitors',
            field=models.TextField(null=True),
        ),
    ]
