# Generated by Django 3.0.7 on 2020-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0007_auto_20200827_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='number_of_employees',
            field=models.CharField(choices=[('fewer-than-10', 'Fewer than 10'), ('10-to-49', '10 to 49'), ('50-to-249', '50 to 249'), ('250-or-more', '250 or More')], max_length=20, null=True),
        ),
    ]
