# Generated by Django 3.1.1 on 2020-10-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0008_auto_20201028_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplication',
            old_name='is_planning_to_grow_exports',
            new_name='has_product_or_service_for_export',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='is_seeking_export_opportunities',
        ),
    ]
