# Generated by Django 3.0.7 on 2020-09-01 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0008_auto_20200901_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='sector_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grant_applications.Sector'),
        ),
    ]
