# Generated by Django 3.1.1 on 2020-10-30 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0009_auto_20201030_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='export_experience_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='export_regions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('africa', 'Africa'), ('asia', 'Asia'), ('australasia', 'Australasia'), ('europe', 'Europe'), ('middle east', 'Middle East'), ('north america', 'North America'), ('south america', 'South America')], max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='export_strategy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='has_exported_in_last_12_months',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='in_contact_with_dit_trade_advisor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='markets_intending_on_exporting_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('existing', 'existing markets'), ('new', 'new markets not exported to in the last 12 months')], max_length=10), null=True, size=None),
        ),
    ]
