# Generated by Django 3.0.7 on 2020-09-01 12:38

from django.db import migrations


def transfer_sectors(apps, schema_editor):
    GrantApplication = apps.get_model('grant_applications', 'GrantApplication')
    Sector = apps.get_model('grant_applications', 'Sector')
    for ga in GrantApplication.objects.all():
        sector = Sector.objects.filter(name=ga.sector)
        if not sector:
            sector = Sector.objects.get(name='Unknown')
        ga.sector_transfer = sector
        ga.save()


def transfer_sectors_reverse(apps, schema_editor):
    GrantApplication = apps.get_model('grant_applications', 'GrantApplication')
    for ga in GrantApplication.objects.all():
        ga.sector_transfer = None
        ga.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0010_create_initial_sector'),
    ]

    operations = [
        migrations.RunPython(transfer_sectors, transfer_sectors_reverse),
    ]
