# Generated by Django 3.1.1 on 2020-11-02 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0011_auto_20201102_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_amount',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_date_awarded',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_date_received',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_description',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_public_authority',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='de_minimis_aid_recipient',
        ),
        migrations.CreateModel(
            name='StateAid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authority', models.CharField(max_length=500)),
                ('date_awarded', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=500)),
                ('grant_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grant_applications.grantapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
