# Generated by Django 3.1.1 on 2020-11-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0012_auto_20201102_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateaid',
            old_name='date_awarded',
            new_name='date_received',
        ),
    ]
