# Generated by Django 3.0.7 on 2020-09-01 13:21

from django.db import migrations, models
import web.grant_applications.models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0012_auto_20200901_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='cluster_name',
            field=models.CharField(default='Unknown', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_code',
            field=models.CharField(default='SL0000', max_length=6, validators=[web.sectors.models.sector_code_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='sub_sector_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='sub_sub_sector_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
