# Generated by Django 3.0.7 on 2020-09-03 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0013_auto_20200901_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_date_awarded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_public_authority',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='de_minimis_aid_recipient',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
