# Generated by Django 3.1.1 on 2020-11-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0013_auto_20201103_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='business_name_at_exhibit',
        ),
        migrations.RemoveField(
            model_name='grantapplication',
            name='website',
        ),
    ]
