# Generated by Django 3.0.7 on 2020-09-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('grant_applications', '0014_auto_20200903_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sectors.Sector'),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
