# Generated by Django 3.1.1 on 2020-10-05 15:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0015_auto_20200917_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='applicant_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='GB'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='applicant_position_within_business',
            field=models.CharField(choices=[('director', 'Director'), ('company-secretary', 'Company Secretary'), ('owner', 'Owner'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
