# Generated by Django 3.1.1 on 2020-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0015_auto_20201105_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplication',
            old_name='company_postcode',
            new_name='manual_company_address_postcode',
        ),
        migrations.RenameField(
            model_name='grantapplication',
            old_name='company_name',
            new_name='manual_company_name',
        ),
        migrations.RenameField(
            model_name='grantapplication',
            old_name='company_type',
            new_name='manual_company_type',
        ),
        migrations.RenameField(
            model_name='grantapplication',
            old_name='time_trading_in_uk',
            new_name='manual_time_trading_in_uk',
        ),
        migrations.RenameField(
            model_name='grantapplication',
            old_name='website',
            new_name='manual_website',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='manual_company_address_county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='manual_company_address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='manual_company_address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='manual_company_address_town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
