# Generated by Django 3.1.1 on 2020-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0016_auto_20201005_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='other_business_names',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
