# Generated by Django 3.1.1 on 2020-11-17 16:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0017_auto_20201111_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='ita_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='ita_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='GB'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='ita_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
