# Generated by Django 3.1.1 on 2020-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0017_grantapplication_other_business_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='is_based_in_uk',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_turnover_greater_than',
            field=models.BooleanField(null=True),
        ),
    ]
