# Generated by Django 3.1.1 on 2021-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0020_auto_20201204_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='evidence_of_event_booking',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
