# Generated by Django 3.1.1 on 2021-03-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0020_auto_20201204_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='is_event_evidence_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_event_evidence_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_event_evidence_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
