# Generated by Django 3.1.1 on 2021-03-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grant_applications', '0021_added_event_evidence_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='event_evidence_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.image'),
        ),
    ]
