# Generated by Django 3.0.7 on 2020-07-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0003_auto_20200731_0839'),
        ('grant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationprocess',
            name='grant_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_application_process', to='grant_applications.GrantApplication'),
        ),
    ]
