# Generated by Django 3.0.7 on 2020-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0003_grantmanagementprocess_employee_count_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='turnover_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
