# Generated by Django 3.0.7 on 2020-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0004_grantmanagementprocess_turnover_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantmanagementprocess',
            name='acknowledge_application',
        ),
        migrations.RemoveField(
            model_name='grantmanagementprocess',
            name='approved',
        ),
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grantmanagementprocess',
            name='employee_count_is_verified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='grantmanagementprocess',
            name='turnover_is_verified',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
