version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    machine:
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Set up .env file
          command: |
            echo "DJANGO_SETTINGS_MODULE=config.settings.ci
            SECRET_KEY=ci-secret-key
            POSTGRES_HOST=db
            POSTGRES_PORT=5432
            POSTGRES_USER=tap
            POSTGRES_DB=tap
            POSTGRES_PASSWORD=tap" > .env
      - run:
          name: Build docker images
          command: make build
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run Tests
          command: make test-ci
      - run:
          name: Generate ERDs
          command: make graph-models
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports/coverage/junitxml

workflows:
  build-and-test:
    jobs:
      - build-and-test
