# Generated by Django 3.0.7 on 2020-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='applicant_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
