# Generated by Django 3.0.7 on 2020-09-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0002_grantapplicationlink_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplicationlink',
            old_name='submitted',
            new_name='sent_for_review',
        ),
    ]
