# Generated by Django 3.1.1 on 2020-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0003_auto_20200918_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationlink',
            name='backoffice_grant_application_id',
            field=models.UUIDField(default='80832bb6-3b97-4453-bd38-3c010de08fa2', unique=True),
            preserve_default=False,
        ),
    ]
