# Generated by Django 3.1.1 on 2020-11-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0005_remove_grantapplicationlink_search_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationlink',
            name='sent_for_review',
        ),
    ]
