# Generated by Django 3.1.1 on 2020-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0006_remove_grantapplicationlink_sent_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationlink',
            name='has_viewed_review_page',
            field=models.BooleanField(default=False),
        ),
    ]
