# Generated by Django 3.1.1 on 2021-02-16 00:15
import uuid

from django.db import migrations, models


def populate_legacy_application_email_addresses(apps, schema_editor):
    GrantApplicationLink = apps.get_model('grant_applications', 'GrantApplicationLink')
    for application in GrantApplicationLink.objects.all():
        application.email = f'legacy_app_{uuid.uuid4().hex}@tap.dit.gov.uk'
        application.save()
    return f'legacy_app_{uuid.uuid4().hex}@tap.dit.gov.uk'


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0007_grantapplicationlink_has_viewed_review_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationlink',
            name='email',
            field=models.EmailField(
                max_length=254,
                blank=True,
                null=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_legacy_application_email_addresses),
        migrations.AlterField(
            model_name='grantapplicationlink',
            name='email',
            field=models.EmailField(unique=True, max_length=254)
        )
    ]
