# Generated by Django 3.1.1 on 2021-02-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0008_added_email_field_to_application_link_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationlink',
            name='state_url_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
