# Generated by Django 3.1.1 on 2021-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0009_added_application_state_url_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationlink',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
