# Generated by Django 3.0.7 on 2020-08-03 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dnb_service_duns_number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
