# Generated by Django 3.0.7 on 2020-09-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200922_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnbgetcompanyresponse',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dnb_get_company_responses', to='companies.Company'),
        ),
    ]
