# Generated by Django 3.1.1 on 2020-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200922_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnbgetcompanyresponse',
            name='data',
            field=models.JSONField(),
        ),
    ]
