# Generated by Django 3.1.1 on 2020-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantmanagementprocess',
            name='employee_count_is_verified',
        ),
        migrations.RemoveField(
            model_name='grantmanagementprocess',
            name='turnover_is_verified',
        ),
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='business_entity_is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='event_commitment_is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='previous_applications_is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='state_aid_is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
