# Generated by Django 3.0.7 on 2020-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0002_auto_20200805_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='employee_count_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
