# Generated by Django 3.0.7 on 2020-09-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0015_auto_20200917_0917'),
        ('grant_management', '0005_auto_20200813_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantmanagementprocess',
            name='grant_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_management_process', to='grant_applications.GrantApplication'),
        ),
    ]
