# Generated by Django 3.1.1 on 2021-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0005_auto_20201120_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmanagementprocess',
            name='event_booking_document_renew_decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
