# Generated by Django 3.0.7 on 2020-08-03 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duns_number', models.IntegerField()),
                ('applicant_full_name', models.CharField(max_length=500, null=True)),
                ('applicant_email', models.EmailField(max_length=254, null=True)),
                ('is_already_committed_to_event', models.BooleanField(null=True)),
                ('is_intending_on_other_financial_support', models.BooleanField(null=True)),
                ('has_previously_applied', models.BooleanField(null=True)),
                ('previous_applications', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('is_first_exhibit_at_event', models.BooleanField(null=True)),
                ('number_of_times_exhibited_at_event', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('goods_and_services_description', models.TextField(null=True)),
                ('business_name_at_exhibit', models.CharField(max_length=500, null=True)),
                ('turnover', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_employees', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sector', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=500, null=True)),
                ('has_exported_before', models.BooleanField(null=True)),
                ('is_planning_to_grow_exports', models.BooleanField(null=True)),
                ('is_seeking_export_opportunities', models.BooleanField(null=True)),
                ('has_received_de_minimis_aid', models.BooleanField(null=True)),
                ('de_minimis_aid_public_authority', models.CharField(max_length=500, null=True)),
                ('de_minimis_aid_date_awarded', models.DateField(null=True)),
                ('de_minimis_aid_amount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('de_minimis_aid_description', models.CharField(max_length=500, null=True)),
                ('de_minimis_aid_recipient', models.CharField(max_length=500, null=True)),
                ('de_minimis_aid_date_received', models.DateField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trade_events.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
