# Generated by Django 3.0.7 on 2020-07-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='has_previously_applied',
            field=models.BooleanField(null=True),
        ),
    ]
