# Generated by Django 3.0.7 on 2020-07-31 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0002_grantapplication_has_previously_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='is_first_exhibit_at_event',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='number_of_times_exhibited_at_event',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='previous_applications',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
