# Generated by Django 3.0.7 on 2020-08-10 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0002_grantapplication_application_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='turnover',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
