# Generated by Django 3.0.7 on 2020-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0003_auto_20200810_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='search_term',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grantapplication',
            name='duns_number',
            field=models.IntegerField(null=True),
        ),
    ]
