# Generated by Django 3.0.7 on 2020-07-31 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0003_auto_20200731_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='business_name_at_exhibit',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='goods_and_services_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='number_of_employees',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='sector',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='turnover',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='website',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
