# Generated by Django 3.0.7 on 2020-07-31 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0004_auto_20200731_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_date_awarded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_date_received',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_public_authority',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='de_minimis_aid_recipient',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='has_exported_before',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='has_received_de_minimis_aid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_planning_to_grow_exports',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_seeking_export_opportunities',
            field=models.BooleanField(null=True),
        ),
    ]
