# Generated by Django 3.0.7 on 2020-08-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_events', '0001_initial'),
        ('grant_applications', '0005_auto_20200731_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trade_events.Event'),
        ),
    ]
