# Generated by Django 3.0.7 on 2020-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_applications', '0005_auto_20200811_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='website',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
